console.log("hello peppa!");

//User profile/application info
var PROFILE = {
    first_name: "Boris",
    last_name: "Kwang",
    email: "uniquepugs223@gmail.com",
    phone: "510-436-7890",
    linkedin: "www.linkedin.com",
    website: "www.facebook.com",
    github: "www.github.com",
    street_address: "1520 Shattuck Avenue",
    city: "Berkeley",
    state: "California",
    zip_code: "94702",
    university: "UC Berkeley",
    degree: "Economics",
    uni_start_month: 8,
    uni_start_year: "2017",
    grad_month: 9,
    grad_year: "2021",
    degree_received: 1,
    employer1: "Robert Half",
    job_title1: "Marketing Analyst",
    current_job1: 0,
    job_location1: "California",
    job_start_month1: 8,
    job_start_year1: "2008",
    job_end_month1: 3,
    job_end_year1: "2009",
    job_desc1: `lead job market efforts,
    doubled retention rates,
    pipeline two million`,
    employer2: "Flybar",
    job_title2: "Associate",
    current_job2: 1,
    job_location2: "California",
    job_start_month2: 3,
    job_start_year2: "2012",
    job_end_month2: 4,
    job_end_year2: "2014",
    job_desc2: `lead job market efforts,
    doubled retention rates,
    pipeline two million`,
    employer3: "",
    job_title3: "Associate",
    current_job3: 1,
    job_location3: "California",
    job_start_month3: 3,
    job_start_year3: "2012",
    job_end_month3: 4,
    job_end_year3: "2014",
    job_desc3: `lead job market efforts,
    doubled retention rates,
    pipeline two million`,
    username: "uniquepugs223",
    password: "Awesomepasword!1",
    question: "bagool",
    answer: "bafool"
}